# Generated by Django 2.0.4 on 2018-05-26 06:45

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bullettin_url', models.URLField(unique=True)),
                ('address', models.TextField()),
                ('apartment_type', models.CharField(max_length=40)),
                ('price_BYN', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('price_USD', models.IntegerField()),
                ('description', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('author_url', models.URLField()),
                ('status', models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=0)),
                ('user_phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=[], size=None)),
                ('user_name', models.CharField(default='UNKNOWN', max_length=96)),
                ('last_updated', models.CharField(default='UNKNOWN', max_length=24)),
                ('image_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None)),
                ('has_balcony', models.BooleanField()),
                ('has_conditioner', models.BooleanField()),
                ('has_fridge', models.BooleanField()),
                ('has_furniture', models.BooleanField()),
                ('has_kitchen_furniture', models.BooleanField()),
                ('has_oven', models.BooleanField()),
                ('has_tv', models.BooleanField()),
                ('has_washing_machine', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApartmentScrapingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('time_finished', models.DateTimeField(auto_now_add=True)),
                ('succeeded', models.BooleanField()),
                ('error_message', models.TextField()),
                ('total_errors', models.PositiveIntegerField()),
                ('total_saved', models.PositiveIntegerField()),
                ('total_active', models.PositiveIntegerField()),
                ('total_inactive', models.PositiveIntegerField()),
            ],
        ),
    ]
