# Generated by Django 2.0.8 on 2019-02-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0005_apartment_has_internet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='RentApartment',
        ),
    ]
