# Generated by Django 2.0.8 on 2019-02-10 15:46

from decimal import Decimal
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0006_auto_20190210_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldApartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bullettin_url', models.URLField(unique=True)),
                ('address', models.TextField()),
                ('apartment_type', models.CharField(max_length=40)),
                ('price_BYN', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('price_USD', models.IntegerField()),
                ('description', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('author_url', models.URLField()),
                ('status', models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=0)),
                ('user_phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=[], size=None)),
                ('user_name', models.CharField(default='UNKNOWN', max_length=96)),
                ('last_updated', models.CharField(default='UNKNOWN', max_length=24)),
                ('image_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None)),
                ('on_floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('total_area', models.FloatField()),
                ('living_area', models.FloatField()),
                ('kitchen_area', models.FloatField()),
                ('house_type', models.TextField()),
                ('balcony_details', models.TextField()),
                ('parking_details', models.TextField()),
                ('ceiling_details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
