# Generated by Django 2.0.8 on 2019-02-10 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0008_auto_20190210_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentscrapingresults',
            name='invalid_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
    ]
