# Generated by Django 2.2.1 on 2019-05-10 04:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0019_auto_20190509_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
        migrations.AlterField(
            model_name='soldapartments',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
