# Generated by Django 2.2.1 on 2019-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0021_auto_20190518_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresults',
            name='search_filter_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
