# Generated by Django 2.2.1 on 2019-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0022_searchresults_search_filter_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='likely_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldapartments',
            name='likely_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
