# Generated by Django 2.2.1 on 2019-08-23 12:25
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0026_auto_20190728_1528'),
    ]

    operations = [
        HStoreExtension(),
    ]
