# Generated by Django 2.2.1 on 2019-08-24 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0028_auto_20190823_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRegion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region_name', models.CharField(db_index=True, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'City Regions',
            },
        ),
    ]
