# Generated by Django 2.2.5 on 2020-02-09 16:21

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderconfiguration',
            name='search_words',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None),
        ),
    ]
