sudo: required
language: ruby
services:
- docker
env:
  matrix:
  - secure: WSkhD/PzMoJpmGsz93h5KKmDVwmPWOLWDCqQRPkNcQrW+tOkd9Y252Bfkjr2f/g3iPSj3PjBCQ5SA+JM/IdhBl8lg+9226Q2mccPtxyrqt1kSV3bI3ra791Fa3ii6UGeZ0Racti6yIlgeCEEdKzKPgGU4DxCSbqeWwm5AmwHZzKEKnWnVedbew3I01DkmF7dyt8I1uq5frfbV9i0no91a+omt2Hc35TlEC2Gk+2jHPMDfVmA6ihQ+dT76Uc1V1+NJVMJjaDJENfe8W1OVl+zmqMrYE3EIHnxrWYHeBXtUbMqEd/bB3gyp9azo6EkXqkkkcIzyObonb3i55/n4xiRLv2HzXqVdVgD43fSj54Fd+0PE7vogJdtcWM+J/3fsbVeuCyys54PzjErEe7UM4C2HY9IKNSv9IwsulWuQ0257HtyDOuB3EFYrNE4lbsrHNeFG38yhBb4994RwTfQGzanF7pNOzvHyz8vi8Y3duCRme6GBX65JVRmzFKsYjU82FBVT2yWTAowv3H3JnOAzGAwUnGt25tEgeqw5z25iBN8QTrTwrWc41CYJN5oyshYFu5r19vu1YthP3vPAQ8AZSGkmQs937dKEEqlInLtNH//3Xbk5Gcmqxxl8J4ZarOrNE3eqjzcUEGJxM9L6z9nLkijGZnBvSRQd24QQfPupGAaQqg=
  - secure: c+qkdbAlHVkOU4FblUf6tzu5Nl+dt1SWXFpc8ok1HIU301GJ7+jZnEnn61TB7dQdwhfWQSijeGjyu303zYYp5G8KLQlFIrI5ihxGUF2ICw1XppIczy+W+kOen2sH7Qd0Hq3tsl7WYikfVT1JJUIJqUd6PLiKQLHx76WF/62p5pUuQGKwTmEeISgJ6iE2mDjemVcV7aVT7Q8M9Wlki1P6pWCMhipwB2ZJJSi4uojzKT9+t6aS6wYzcSsTYuLRYGAWX9Xf1DF3jx/d/zyU/HovUGI8O3WR7SVV1dMxtmVfeHgl8mPTowzslbp59vVJZfDRsYiA0c0wAefKUyOQirXCe1nl2V9ghQcC5d10PphJrssb4IfgdxSScssGt7oTTIPWmVsF+XEKVoSCGz/6mTdSQqmhgW2FhZ+QNyaYeDl3xvQJrkxMhLXrEa45DcnABOkuzkwcA4HLpI5z3VdEXYL0bk5dZG8YjzeIaxcZ9JC8OzTGeil89I/S2QHzxDDwKit3DmHGB+Qws2YRIbVfoE7P3AHGtrtUqL+jVzHfyaIFJC3rfIU1q2bsA/NZkcAFlqsCUAYTua/5CUSyYLVYUul9iLDGU9MLQ48LuPuSrxYkVTHoDHcrYUmkYlQTi7FxRmXtCdWssHgb/Y9cmC3uSav3woibgpN0axrhPypXr4OFqs8=

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: develop