sudo: required
language: python

services:
  - docker

jobs:
  include:
    - stage: Build and push docker image
      script: 'bash docker_push.sh'
      on:
        branch: develop
      if: type != cron
