sudo: required
language: python
services:
- docker

env:
  matrix:
  - secure: ARTfKX7v5sm4EFD8KrbxDsQLhofhQeWiY8612dGOsff1CejOLGoBxE5PvgrNdGzvVjjgmb0ArIdYcr60ws/6uiGuaQdm65qrgNen03Se94gicy7ZTMzuJ2ZecC6ra3KbjuD8LratQlpcuEQQHWH26CfEk9MdlA08lhfSZWnh1oNzeGaXehb8IS6dLlbUSN0HZyi3lIBE7Eieho8bB3HctQD1M2ml2m/XUGgytY2psxaNz8Ke9JAnUDU3l+y8izg2+ayepI3bnc3PLkAKDi6so7lyDEHrkSDkrnbblX/0+zHNxO0cq+TG0CCfyTKPeQQuwvzI8aFbyLBMUD+YZNMJmeDJp4sA8GDLjLRh0nLNgJ1ZFntVFtT3dVbYBOiZ2Cu+xBOdTv8pWpi2eKjpD064Ty5fsZZvsldBg6iNv79e164gduQKlBmqbcT3eCHGdp9fqZ1A8On8dLn2Ej2irufUWRYeAEJ0GX30NIQaEive+nQUBOavJ9tkHHeLgyyEIDdpvG+a/g7hN0Y12MfKsC3uMMlxDkJA3uhSCLaLBzpRCXj3qDagCfK6Q/f2ee7YryffN+Rh7WfdTgwirrvvmVZVaCS81LdRdSHYmhfP9tP/3VWL1tag8LytDacJX2b0qrJAyflZWdLjT8t8BOA0f2cHNSc5VBQSM1mFesNE71/54ag=

install:
  - pip install tox

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: develop
