version: '2.1'

networks:
  sentry_network:
    driver: bridge


services:

  database:
    extends:
      file: docker-compose.base.yml
      service: database


  messagebus:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  # Django back-end
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash entrypoint.sh --prod
    env_file:
      - ./environment/backend.env
      - ./environment/db.env
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
      - ./static/:/app/personal_site/staticfiles
    working_dir: /app/
    links:
      - messagebus
      - redis
    networks:
      - sentry_network
    depends_on:
      database:
        condition: service_healthy

  celery-worker:
    extends:
      file: docker-compose.base.yml
      service: celery-worker
    links:
      - redis
      - messagebus

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Build frontend one time
    # and reuse its static files
    command: ./entrypoint-prod.sh
    volumes:
      - ./frontend/:/frontend/
