version: '2'

services:
  
  # Django back-end
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
    working_dir: /app/

volumes:
  frontend-data:
  database-data: