version: '2'

services:
  db:
    image: postgres:9.4
    env_file: .env
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  kv_storage:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: ./
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "2222:22"
      - "8000:8000"
