version: '2'

services:
  # This container is data-only
  # It is used to provide storage volume for the postgres container
  # https://medium.com/@ramangupta/why-docker-data-containers-are-good-589b3c6c749e
  postgres_data:
    image: alpine:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    command: "true"

  database:
    restart: always
    image: postgres:9.4.4
    env_file: ./docker-env/db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes_from:
      - postgres_data
    ports:
      - "15432:5432"

  redis:
    image: redis
    ports:
      - "16379:6379"

  web:
    restart: always
    build: .
    env_file:
      - ./docker-env/db.env
      - ./docker-env/settings.env
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.dev_integration
    volumes:
      - ./personal_site:/personalsite
      - ./personal_site/staticfiles:/static
    command: bash -c "python manage.py loaddata about_me/fixures/fixtures.yml python manage.py migrate; gunicorn -w 4 -b :8000 personal_site.wsgi:application"
    ports:
      - "8001:8000"
    links:
      - database
      - redis

  nginx:
    restart: always
    tty: true
    build: ./nginx/
    ports:
      - "8080:80"
    volumes_from:
      - web
    links:
      - web