version: '3.2'

networks:
  production_network:
    driver: bridge


services:

  database:
    image: postgres:10.2-alpine
    volumes:
      - ./pgdata-prod/:/var/lib/postgresql/data
    env_file:
      - ./.env

  messagebus:
    image: rabbitmq:3.6.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbit-data/:/var/lib/rabbitmq
    networks:
      - production_network
    logging:
      driver: none


  redis:
    image: redis:3.0.7-alpine
    ports:
      - "6379:6379"

  # Django back-end
  backend:
    restart: always
    image: registry.mrlokans.com:5000/personal_site:${BACKEND_VERSION:-latest}
    command: --prod
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.prod
      - DATABASE_HOST=database
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
      - ./static/:/app/personal_site/staticfiles
      - ./cron-logs/:/var/log/cron/
    working_dir: /app/
    networks:
      - production_network
    depends_on:
      - database