version: '2'

services:
  database:
    image: postgres:9.4.4
    env_file: .env
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"

  redis:
    image: redis
    ports:
      - "16379:6379"

  web:
    build: ./personal_site
    env_file: .env
    ports:
      - "2222:22"
      - "8000:8000"
    command: gunicorn -w 2 -b :8000 personal_site.wsgi:application
