version: '3.2'

networks:
  production_network:
    driver: bridge

services:

  database:
    restart: unless-stopped
    image: mdillon/postgis:10-alpine
    volumes:
      - ./pgdata-postgis-prod/:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - production_network

  redis:
    restart: unless-stopped
    image: redis:5.0.6-alpine
    networks:
      - production_network

  # Django back-end
  backend:
    restart: unless-stopped
    image: registry.mrlokans.com:5000/personal_site:${BACKEND_VERSION:-latest}
    command: --prod
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=database
    ports:
      - "8000:8000"
    volumes:
      - ./static/:/app/personal_site/staticfiles
      - ./cron-logs/:/var/log/cron/
    working_dir: /app/
    networks:
      - production_network
    depends_on:
      - database
      - redis

  # Django back-end
  apartment_notifier_bot:
    restart: unless-stopped
    image: registry.mrlokans.com:5000/personal_site:${BACKEND_VERSION:-latest}
    command: --bot
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=database
    ports:
      - "8000:8000"
    working_dir: /app/
    networks:
      - production_network
    depends_on:
      - database
      - redis

  # Django back-end
  async_tasks_worker:
    restart: unless-stopped
    image: registry.mrlokans.com:5000/personal_site:${BACKEND_VERSION:-latest}
    command: --async_tasks
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=database
    working_dir: /app/
    networks:
      - production_network
    depends_on:
      - database
      - redis