version: '2.0'

services:
  
  messagebus:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq

  redis:
    extends:
      file: docker-compose.base.yml
      service: redis

  # Django back-end
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash ./entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.dev
    env_file:
      - bus.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
      - ./static/:/app/personal_site/staticfiles
    # Enables PDB debugging
    stdin_open: true
    tty: true
    working_dir: /app/
    links:
      - messagebus
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    env_file:
      - bus.env
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "8090:8090"

  celery-worker:
    extends:
      file: docker-compose.base.yml
      service: celery-worker
    links:
      - redis
      - messagebus

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./static/:/static/
    volumes_from:
      - frontend
    depends_on:
      - backend
      - frontend
    links:
      - backend

volumes:
  frontend-data:
  database-data: