version: '2'

services:
  
  # Django back-end
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
    working_dir: /app/

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./frontend/:/static/
    ports:
      - "8090:8090"

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes_from:
      - frontend
    depends_on:
      - frontend

volumes:
  frontend-data:
  database-data: