# Only for the local development
version: '3.2'

networks:
  backend_network:
    driver: bridge

services:

  database:
    image: postgres:10.2-alpine
    env_file:
      - ./.env
    networks:
      - backend_network
    ports:
      - "15432:5432"
    volumes:
      - ./.pgdata-dev/:/var/lib/postgresql/data

  messagebus:
    image: rabbitmq:3.6.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbit-data/:/var/lib/rabbitmq
    networks:
      - backend_network
    logging:
      driver: none

  redis:
    image: redis:3.0.7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend_network

  # Django back-end
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
      - ./static/:/app/personal_site/staticfiles
      - ./cron-logs/:/var/log/cron/
    # Enables PDB debugging
    stdin_open: true
    tty: true
    working_dir: /app/
    networks:
      - backend_network
    restart: always
    depends_on:
      - database

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./static/:/static/
    networks:
      - backend_network
    env_file:
      - ./.env

volumes:
  database-data:
