version: '2'

services:
  
  # Django back-end
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=personal_site.settings.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
      - ./static/:/app/personal_site/staticfiles
    # Enables PDB debugging
    stdin_open: true
    tty: true
    working_dir: /app/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./frontend/:/frontend/
    ports:
      - "8090:8090"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./static/:/static/
    volumes_from:
      - frontend
    depends_on:
      - backend
      - frontend
    links:
      - backend

volumes:
  frontend-data:
  database-data: