# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_auto_20170107_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'open_source'), (2, 'volunteer'), (3, 'enterprise')], null=True),
        ),
    ]
