---
- name: Install required dependencies
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - sqlite-devel
    - gcc
    - python-devel

- name: Create download dir
  file:
    path: Python
    state: directory

- name: Download python src
  get_url:
    url: "{{ python_ftp_url }}/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: Python

- name: Download signature
  get_url:
    url: "{{ python_ftp_url }}/{{ python_version }}/Python-{{ python_version }}.tgz.asc"
    dest: Python

- name: Copy pubkey list
  get_url:
    url: "https://www.python.org/static/files/pubkeys.txt"
    dest: Python

- name: import public keys
  command: gpg --import pubkeys.txt
  args:
    chdir: Python

- name: Verify signature
  command: gpg --verify Python-{{ python_version }}.tgz.asc
  args:
    chdir: Python

- name: Extract sources
  command: tar xzf Python-{{ python_version }}.tgz
  args:
    chdir: Python

- name: Configure installation
  command: ./configure --prefix=/usr/local LDFLAGS="-Wl,-rpath /usr/local/lib"
  args:
    chdir: Python/Python-{{ python_version }}

- name: Build python and install it, replacing original version
  shell: make && make altinstall
  args:
    chdir: Python/Python-{{ python_version }}

# - name: Cleanup environment
#   file: path=Python state=absent