# Generated by Django 2.0.4 on 2018-07-06 04:45

from django.db import migrations


TZ_FROM, TZ_TO = 'UTC', 'Europe/Minsk'


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0003_auto_20180701_1550'),
    ]

    operations = [
    ]
