# Generated by Django 2.0.4 on 2018-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0004_auto_20180706_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_internet',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
