# Generated by Django 2.0.8 on 2019-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0007_soldapartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldapartments',
            name='ceiling_details',
            field=models.TextField(default=''),
        ),
    ]
