# Generated by Django 2.0.8 on 2019-03-17 13:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0009_auto_20190210_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentapartment',
            name='image_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='rentapartment',
            name='user_phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='soldapartments',
            name='image_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='soldapartments',
            name='user_phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), default=list, size=None),
        ),
    ]
