# Generated by Django 2.0.8 on 2019-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0010_auto_20190317_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='last_active_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldapartments',
            name='last_active_parse_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
