# Generated by Django 2.0.8 on 2019-03-24 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0011_auto_20190317_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='subway_distances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='soldapartments',
            name='subway_distances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
