# Generated by Django 2.2.1 on 2019-05-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0017_migrate_to_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapartment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='rentapartment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='soldapartments',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soldapartments',
            name='longitude',
        ),
    ]
