# Generated by Django 2.2.1 on 2019-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0020_auto_20190510_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersearch',
            options={'verbose_name_plural': 'Persisted user searches'},
        ),
        migrations.AddField(
            model_name='usersearch',
            name='search_version',
            field=models.PositiveIntegerField(default=0, help_text='Number of search modifications'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='max_price',
            field=models.PositiveIntegerField(help_text='Максимальная цена в $'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='min_price',
            field=models.PositiveIntegerField(default=0, help_text='Минимальная цена в $'),
        ),
    ]
