# Generated by Django 2.2.1 on 2019-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0024_auto_20190703_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='report_likely_agents',
            field=models.BooleanField(default=True),
        ),
    ]
