# Generated by Django 2.2.1 on 2019-07-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0025_usersearch_report_likely_agents'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersearchcontact',
            constraint=models.UniqueConstraint(fields=('contact_type', 'contact_identifier'), name='unique_contact'),
        ),
    ]
