# Generated by Django 2.2.1 on 2019-08-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0027_auto_20190823_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='max_price',
            field=models.PositiveIntegerField(default=300, help_text='Максимальная цена в $'),
        ),
    ]
