# Generated by Django 2.2.5 on 2020-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0029_cityregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearchcontact',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
    ]
