# Generated by Django 2.2.5 on 2020-02-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0030_usersearchcontact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='min_rooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Минимальное количество комнат'),
        ),
    ]
