# Generated by Django 2.2.5 on 2020-02-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0031_usersearch_min_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
