# Generated by Django 3.0.4 on 2020-04-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0032_usersearch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapartment',
            name='total_rooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soldapartments',
            name='total_rooms',
            field=models.IntegerField(null=True),
        ),
    ]
