- include: checkout.yml
- include: virtualenv.yml
# - include: gunicorn.yml

- name: Install binary dependencies
  yum: name={{ item }} state=present
       update_cache=yes
  with_items:
    - libxml2-devel
    - libjpeg-devel
    - libxslt-devel
    - zlib-devel

- name: Install required dependencies
  command: "{{ project_venv }}/bin/pip install -r {{ project_root }}/requirements/base-requirements.txt"  
  args:
    chdir: "{{ project_root }}/personal_site"
  become: yes
  become_user: "{{ project_user }}"

- name: Run migrations
  command: "{{ project_venv }}/bin/python3.5 manage.py migrate --run-syncdb"
  args:
    chdir: "{{ project_root }}/personal_site"
  become: yes
  become_user: "{{ project_user }}"

- name: Collect static files
  command: "{{ project_venv }}/bin/python manage.py collectstatic"
  args:
    chdir: "{{ project_root }}/personal_site"
  become: yes
  become_user: "{{ project_user }}"

- name: Copy nginx configuration file
  template: src=mrlokans.com.conf.j2
            dest=/etc/nginx/sites-available/mrlokans.com

- name: Create symlink to config
  file: src=/etc/nginx/sites-available/mrlokans.com
        dest=/etc/nginx/sites-enabled/mrlokans.com
        state=link

# - name: Restart nginx
