- include: checkout.yml
- include: virtualenv.yml
- include: gunicorn.yml

- name: Install binary dependencies
  yum: name={{ item }} state=present
       update_cache=yes
  with_items:
    - libxml2-devel
    - libjpeg-devel
    - libxslt-devel
    - zlib-devel

- name: Install required dependencies
  command: "{{ project_venv }}/bin/pip install -r {{ project_root }}/requirements/base-requirements.txt"  
  args:
    chdir: "{{ project_root }}/personal_site"
  become: yes
  become_user: "{{ project_user }}"
  environment:
    PERSONAL_SITE_SECRET_KEY: "{{ project_secret_key }}"
    DJANGO_SETTINGS_MODULE: "{{ project_settings_module }}"

- name: Run migrations
  command: "{{ project_venv }}/bin/python3.5 manage.py migrate --run-syncdb"
  args:
    chdir: "{{ project_root }}/personal_site"
  environment:
    PERSONAL_SITE_SECRET_KEY: "{{ project_secret_key }}"
    DJANGO_SETTINGS_MODULE: "{{ project_settings_module }}"
  become: yes
  become_user: "{{ project_user }}"

- name: Install front-end dependencies with bower
  command: "{{ project_venv }}/bin/python manage.py bower install"
  args:
    chdir: "{{ project_root }}/personal_site"
  become: yes
  become_user: "{{ project_user }}"
  environment:
    PERSONAL_SITE_SECRET_KEY: "{{ project_secret_key }}"
    DJANGO_SETTINGS_MODULE: "{{ project_settings_module }}"
    STATIC_DIR: "{{ project_static_dir }}"

- name: Collect static files
  command: "{{ project_venv }}/bin/python manage.py collectstatic --noinput"
  args:
    chdir: "{{ project_root }}/personal_site"
  become: yes
  become_user: "{{ project_user }}"
  environment:
    PERSONAL_SITE_SECRET_KEY: "{{ project_secret_key }}"
    DJANGO_SETTINGS_MODULE: "{{ project_settings_module }}"
    STATIC_DIR: "{{ project_static_dir }}"

- name: Copy launching script
  template: src=run-mrlokans.sh.j2
            dest={{ project_root }}/run-mrlokans.sh

- name: Set executice bit on script
  file: name={{ project_root }}/run-mrlokans.sh
        mode="u+x,g+x"

- name: Copy supervisord config
  template: src=personalsite-supervisord.conf.j2
            dest=/etc/supervisord.d/personalsite.conf

- name: Restart supervisord
  service: name=supervisord
           state=restarted

- name: Stop process if it is running
  supervisorctl: name={{ project_supervisor_name }}
                 state=stopped
                 config=/etc/supervisord.conf
  ignore_errors: true

- name: Start process
  supervisorctl: name={{ project_supervisor_name }}
                 state=started
                 config=/etc/supervisord.conf

# - name: Copy nginx configuration file
#   template: src=mrlokans.com.conf.j2
#             dest=/etc/nginx/sites-available/mrlokans.com

# - name: Create symlink to config
#   file: src=/etc/nginx/sites-available/mrlokans.com
#         dest=/etc/nginx/sites-enabled/mrlokans.com
#         state=link

# - name: Restart nginx
