---
- hosts: andersblog-centos

  vars:
    project_user: personalsite
    project_group: personalsite
    project_root: /opt/personalsite
    project_repo: https://github.com/MrLokans/portfoliosite
    project_revision: master
    project_venv: "{{ project_root }}/venv"
    project_static_dir: /opt/personalsite/static
    project_gunicorn_bind: 127.0.0.1:8099

    project_configuration: dev

    use_tls: false
    dh_key_path: /etc/nginx/ssl/dh.key
    ssl_certificate: /etc/letsencrypt/live/mrlokans.com/fullchain.pem;
    ssl_certificate_key: /etc/letsencrypt/live/mrlokans.com/privkey.pem;

    # Only for development
    project_secret_key: SOMESECRETKEY
    project_settings_module: personal_site.settings.jenkins
    project_domain_name: mrlokans.com

    project_supervisor_name: mrlokans


  roles:
    - epel
    - supervisord
    - git
    - python3.5
    - _users
    - node
    - nginx
    - project