# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('author_url', models.URLField()),
                ('bullettin_url', models.URLField()),
                ('status', models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
