# Generated by Django 2.0.4 on 2018-05-26 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentscrapingresults',
            name='invalid_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=[], size=None),
        ),
    ]
