# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentScrapingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField()),
                ('time_finished', models.DateTimeField(auto_now_add=True)),
                ('succeeded', models.BooleanField()),
                ('error_message', models.TextField()),
                ('total_errors', models.PositiveIntegerField()),
                ('total_saved', models.PositiveIntegerField()),
                ('total_active', models.PositiveIntegerField()),
                ('total_inactive', models.PositiveIntegerField()),
            ],
        ),
    ]
