# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-23 18:15
from __future__ import unicode_literals

from django.db import migrations, transaction, IntegrityError

from apartments_analyzer.deduplicator import Deduplicator


def deduplicate_bullettins(apps, schema_editor):
    """
    After this migration we make sure that
    all the origin_urls fields become primary_keys
    which will raise an Integrity error in case
    the duplicates are found in the database, so
    we explicitly merge all of them.
    """
    Apartment = apps.get_model('apartments_analyzer',
                               'Apartment')
    deduplicator = Deduplicator(Apartment, 'bullettin_url')
    deduplicator.remove_duplicate_apartments()


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0002_apartmentscrapingresults'),
    ]

    operations = [
        migrations.RunPython(deduplicate_bullettins),
    ]
