# Generated by Django 2.0.4 on 2018-07-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments_analyzer', '0002_apartmentscrapingresults_invalid_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentscrapingresults',
            name='new_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentscrapingresults',
            name='updated_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
