# Generated by Django 2.0.4 on 2018-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_number_of_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNameMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming_book_name', models.CharField(max_length=200)),
                ('output_title', models.CharField(max_length=200)),
                ('output_author', models.CharField(max_length=200)),
            ],
        ),
    ]
