# Generated by Django 2.0.4 on 2018-06-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_booknamemapper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Book',
            old_name='title',
            new_name='original_title',
        )
    ]
