- name: Install git
  when: ansible_os_family == 'Debian'
  apt: name={{ item }} state=present
  with_items: 
    - git

- name: Install git
  when: ansible_os_family == 'RedHat'
  yum: name={{ item }} state=present
  with_items: 
    - git