# Generated by Django 2.0.8 on 2018-09-24 17:16

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_conferencetalkpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencetalkpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
